//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCMTLCB1WebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LCMTLCB1WebApplication.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award.
        /// </summary>
        public static string Award {
            get {
                return ResourceManager.GetString("Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berth Schedule.
        /// </summary>
        public static string Berth_Schedule {
            get {
                return ResourceManager.GetString("Berth Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Inquiry.
        /// </summary>
        public static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Search.
        /// </summary>
        public static string Booking_Search {
            get {
                return ResourceManager.GetString("Booking Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        public static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFS Appointment Online (LCL).
        /// </summary>
        public static string CFS_Online_LCL {
            get {
                return ResourceManager.GetString("CFS Online LCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Shore Online.
        /// </summary>
        public static string Check_Shore_Online {
            get {
                return ResourceManager.GetString("Check Shore Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Inquiry.
        /// </summary>
        public static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Search.
        /// </summary>
        public static string Container_Search {
            get {
                return ResourceManager.GetString("Container Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Status.
        /// </summary>
        public static string Container_Status {
            get {
                return ResourceManager.GetString("Container Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Shore Online.
        /// </summary>
        public static string Create_Shore_Online {
            get {
                return ResourceManager.GetString("Create Shore Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ePayment.
        /// </summary>
        public static string e_Payment {
            get {
                return ResourceManager.GetString("e-Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Quick Search.
        /// </summary>
        public static string e_Quick_Search {
            get {
                return ResourceManager.GetString("e-Quick Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Terminal.
        /// </summary>
        public static string e_Terminal {
            get {
                return ResourceManager.GetString("e-Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Tracking.
        /// </summary>
        public static string e_Tracking {
            get {
                return ResourceManager.GetString("e-Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility.
        /// </summary>
        public static string Facility {
            get {
                return ResourceManager.GetString("Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallerry.
        /// </summary>
        public static string Gallerry {
            get {
                return ResourceManager.GetString("Gallerry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Charge.
        /// </summary>
        public static string Import_Charge {
            get {
                return ResourceManager.GetString("Import Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Support Center.
        /// </summary>
        public static string IT_Support_Center {
            get {
                return ResourceManager.GetString("IT Support Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;LCB1 Group&lt;/strong&gt; is one of the leading container terminal operators in Laem Chabang Port providing world class service to our customers.&lt;br /&gt;&lt;br /&gt;
        ///            &lt;strong&gt;At LCB1 Group, “Driving our Performance”, “Compliance”, Good Corporate Governance”&lt;/strong&gt; and &lt;strong&gt;“Focus on Safety and Environment”&lt;/strong&gt; are integral parts of our work culture.&lt;br /&gt;&lt;br /&gt;
        ///            We are also committed to &lt;strong&gt;“Constant Improvements”&lt;/strong&gt; and &lt;strong&gt;“Close Communication”&lt;/strong&gt; with our c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LCB_Profile {
            get {
                return ResourceManager.GetString("LCB_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Team.
        /// </summary>
        public static string Management_Team {
            get {
                return ResourceManager.GetString("Management Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are highly expertise in container terminal management for international standard, specializes in service of container freight station, empty container storage, repairing, cleaning, and warehousing which related to business..
        /// </summary>
        public static string Mission_detail {
            get {
                return ResourceManager.GetString("Mission detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Service.
        /// </summary>
        public static string Online_Service {
            get {
                return ResourceManager.GetString("Online Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview Calls.
        /// </summary>
        public static string Overview_Call {
            get {
                return ResourceManager.GetString("Overview_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Induction for External Trucker.
        /// </summary>
        public static string Safety_Induction_for_External_Trucker {
            get {
                return ResourceManager.GetString("Safety Induction for External Trucker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA&lt;br&gt;
        ///&lt;strong&gt;BBB&lt;/strong&gt;&lt;br&gt;
        ///C&lt;span style=&quot;color:red&quot;&gt;CC&lt;/span&gt;CC.
        /// </summary>
        public static string TestDetail {
            get {
                return ResourceManager.GetString("TestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTT Dashboard.
        /// </summary>
        public static string TTT_Dashboard {
            get {
                return ResourceManager.GetString("TTT Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision &amp; Mission.
        /// </summary>
        public static string Vision_and_Mission {
            get {
                return ResourceManager.GetString("Vision and Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be the Container Terminal of Choice in Laem Chabang by providing safe, consistent and competitive productivity delivered by a possionate workforce relentlessly applying LEAN..
        /// </summary>
        public static string Vision_detail {
            get {
                return ResourceManager.GetString("Vision detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to LCB1 and  LCMT.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to E-Terminal.
        /// </summary>
        public static string WelcomeToE_Terminal {
            get {
                return ResourceManager.GetString("WelcomeToE_Terminal", resourceCulture);
            }
        }
    }
}
